project:
  type: website
  output-dir: docs
  post-render:
    - ./postrender.sh

website:
  title: "REINE Lab"
  description: "Resilience, Energy, and Inequity in Neighborhood Environments"
  navbar:
    title: "REINE Lab"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "People"
        href: people.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "News"
        href: news.qmd
      - text: "Photography"
        href: photos.qmd
    right:
      - icon: envelope
        href: mailto:misbath.d@berkeley.edu
      - icon: github
        href: https://github.com/reinelab
  page-footer:
    center: "© 2026 REINE Lab"

format:
  html:
    theme: theme.scss
    css: styles.css
    toc: false
    grid:
      body-width: 1100px
